version: '3.9'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demodb
    volumes:
      - /data/mysql
  
  crm-app:
    image: crm-appv1
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
      
    ports:
      - 6062:6060
    volumes:
      - /data/compose-app